### ISSUE TITLE
Better UX when adding more than 10 items to carousel

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens#1]
Issue:
When using the carousel generator to create a carousel of more than 10 items, the user has to manually edit the URL as the form only exposes 10 fields.

Steps to reproduce:
Visit the carousel generator page and try to add more than 10 items.

Solution:
It would be great to have new URL fields auto-added as you start to use them up.

**Comment by georgecrawford** [comment]
This should also work when pasting an existing generator URL into the first field.
