### ISSUE TITLE
OBS conflicts

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens#102]
We have Origami component conflicts in our requests to the build-service --  http://ftlabs-screens.herokuapp.com/generators/image/?https%3A%2F%2Fimage.webservices.ft.com%2Fv1%2Fimages%2Fraw%2Fhttp%253A%252F%252Fi.imgur.com%252FoUOvXb1.jpg%3Fsource%3Dscreens&title=oUOvXb1.jpg (edited)

This is the conflicting bundle URL: http://build.origami.ft.com/v2/bundles/css?modules=o-fonts@^1.6.7,o-ft-icons@^2.3.6,o-header,o-grid,o-forms,o-colors,o-buttons

It seems we are using no version range on most of the modules there which is a bad practice. We should ideally be using caret versions for each of the modules in the URL at least.

**Comment by seanmtracey** [comment]
LGTM

**Comment by AdaRoseCannon** [comment]
Fixed by #103

**Comment by JakeChampion** [comment]
It's yet to go live. Should be today.

**Comment by rowanmanning** [comment]
Thank you! :tada:

<img width="567" alt="screen shot 2016-03-30 at 15 26 58" src="https://cloud.githubusercontent.com/assets/138944/14145476/ef5520ea-f68b-11e5-82c7-d3af40065469.png">

**Comment by AdaRoseCannon** [comment]
:bow:
