### ISSUE TITLE
Bundle Compilation Errors

### ISSUE THREAD

**Issue by rowanmanning** [ftlabs/screens#120]
[This page](http://ftlabs-screens.herokuapp.com/generators/image/?https%3A%2F%2Fimage.webservices.ft.com%2Fv1%2Fimages%2Fraw%2Fhttp%253A%252F%252Fimgur.com%252FcaM6UNA.jpg%3Fsource%3Dscreens&amp;title=caM6UNA.jpg) is triggering a lot of bundle compilation errors in the Build Service – the Sass no longer compiles. It's not super urgent, but it looks bad in our monitoring 😁

**Comment by JakeChampion** [comment]
This has been fixed :-)
