### ISSUE TITLE
Feedback if link can't be displayed in an iFrame

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/screens#13]
Currently, if a user tries to assign a web address to a screen that uses iFrames to display content (Chrome), and the site doesn't like being in an iFrame, we display a blank page until it either expires or someone notices and assigns content that does work. 

What if, instead of sending the site of to be displayed willy-nilly, we request the headers of the site first and check if it's deployable? We could then alert the user in the admin panel that the content can't be displayed.

**Comment by AdaRoseCannon** [comment]
We could do the check in the same request in which we get get the title and warn appropriately. But it wouldn't really work in carousels. Although the carousel doesn't seem to use the transformUrls module anymore is this now done somewhere else now?

**Comment by seanmtracey** [comment]
Currently under review in #47, still needs a little UI love.

**Comment by JakeChampion** [comment]
#47 now merged, deployed to test. Picture of the work done to be added to this issue.

**Comment by JakeChampion** [comment]
No Hover
![no_hover](https://cloud.githubusercontent.com/assets/913687/11718847/ec089ce8-9f4f-11e5-9239-7e2c6935e96a.png)
::hover
![on_hover](https://cloud.githubusercontent.com/assets/913687/11718850/ef74acdc-9f4f-11e5-96b8-aa60020d2b76.png)

**Comment by AdaRoseCannon** [comment]
That bug appears to be fixed on screens-test, closing this issue.
