### ISSUE TITLE
Admin UI tweaks

### ISSUE THREAD

**Issue by triblondon** [ftlabs/screens#22]
While we're working on screens, can I request a couple of very simple changes:
- Move the X that de-assigns content next to the title (so make it inline, just after the end of the title text)
- Move the screen ID into a new column to the _left_ of the screen name (and remove the brackets and hash prefix)

**Comment by seanmtracey** [comment]
In-progress in branch [https://github.com/ftlabs/screens/tree/ui-tweaks](ui-tweaks)

**Comment by JakeChampion** [comment]
From https://github.com/ftlabs/screens/pull/55 -- ![](https://cloud.githubusercontent.com/assets/913687/11782896/d2edb972-a26b-11e5-89d9-6da3fb37772c.png)

**Comment by JakeChampion** [comment]
Resolved by - https://github.com/ftlabs/screens/pull/55
