### ISSUE TITLE
Scheduler for screens is not working correctly

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens#23]
When adding an item to a screen and scheduled for right now, the item ended up being adding to the bottom of the list. As the item was at the bottom of the list it made me think it was scheduled for the past.

I also noticed another screen which had the second item in it's stack as the active item being displayed. This made me think the first item is scheduled for some time in the future. We used to display "Scheduled at" times next to items which were scheduled for some time in the future. Was this removed, and if so, why was this removed? As I can't remember.

Chris and myself also noticed a possible issue whereby the computer displaying the content might be a in a different timezone than the computer on the admin panel, we are not sure if the scheduler will work correctly in this situation.

**Comment by railsagainstignorance** [comment]
have just tested adding a future scheduled url to my screen, and it seems to display the "Scheduled for Fri Dec 04 2015 14:36:00 GMT+0000 (expires in a day) " ok.

**Comment by railsagainstignorance** [comment]
perhaps, as a start, report in the server logs all the Viewers times/timezones so we can see where the Viewer PCs are out of whack.

**Comment by railsagainstignorance** [comment]
ditto, being able to display (on request, in the admin screen) the explicit data we hold on each viewer screen.

**Comment by AdaRoseCannon** [comment]
Timezones should be fine since it is scheduled to the nearest minute using unix timestamp.

**Comment by JakeChampion** [comment]
I'm not sure what rounding strategy we use, I think we should always round-up to the nearest minute (we hopefully already do that).

**Comment by triblondon** [comment]
Does anyone ever actually schedule content?  We added it because it was considered 'essential' but I don't think I've ever seen it used.

**Comment by AdaRoseCannon** [comment]
This feature is being deprecated.
