### ISSUE TITLE
Carousel titles don't persist when pasted into the admin area

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/screens#24]

**Comment by AdaRoseCannon** [comment]
@seanmtracey can you elaborate? 

As in when you paste links the new title overrides the old one and you think it should only update if the title box has the default text?

Or

When you assign a carousel the admin page forgets the title and shows something else?

**Comment by seanmtracey** [comment]
If I generate a carousel with a title, copy the generated URL, close the admin view and then use that URL I copied, all is well. If I copy the URL I generated from the URL bar/some other place and paste it into a new admin view, the input boxes with the URLs get repopulated, but the title of the carousel doesn't. Isn't that something we'd want to keep when we parse the URL?
