### ISSUE TITLE
Prevent DOSing a site via the carousel

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens#32]
An issue was spotted today where a carousel had no duration times specified, this caused the carousel to switch continuously between the websites.

A hot-fix went in to master which resolved the issue by checking if the duration is a falsy value, if it is falsy we now set the default duration time of 10 seconds.

Recommend steps to make the carousel more robust:
- [x] Parse the duration (d) parameter into an integer and check it is actually an integer.
- [x] Have a range of sensible duration values (E.G. More than 2 seconds, less than 50,000 seconds).
- [ ] Have the duration start counting once the page has fully loaded.

**Comment by triblondon** [comment]
Agree with all the above.

**Comment by seanmtracey** [comment]
Ada asked for this to deal with #42
