### ISSUE TITLE
Introduce Heroku Docker deployment workflow to align with other projects

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens#39]
I just tried to run the application and had an error when I requested the `/logs` endpoint as I don't have Redis on this machine. Instead of installing Redis on each machine, I think it would be better if we use Docker for local development as it can house dependencies such as Redis quite nicely. On top of that, it would also bring this project in line with other Labs and Origami projects which have moved to using Heroku with Docker for development and deployment.

**Comment by AdaRoseCannon** [comment]
You could use an env variable to set the redis to go url to ftlabs-screens-test redis?

**Comment by railsagainstignorance** [comment]
hm. strongly against that. Would invite if not demand clashes between multiple users in the same instance.

**Comment by railsagainstignorance** [comment]
back to JC's orig issue: sounds like a nice idea. If it is not mucho effort, would be good to try.
