### ISSUE TITLE
screen name change bug

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/screens#48]
I witnessed Junior set up a new viewer, then go to the supplied admin url, the page lists just his new screen (#40924), assigned content. This worked.

He then changed the screen name to "B2B something or other", and this worked on his admin view, but not on the general admin view. I still see the "Screen #40924" name.

**Comment by seanmtracey** [comment]
This should be resolved by #40. Unsure whether or not it's made it's way to the master branch yet.

**Comment by JakeChampion** [comment]
Fixed in #40 and is now live
