### ISSUE TITLE
refactor/port url/content processing from server to viewer

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/screens#58]
move the url/content processing logic from server to the viewer, so that the server acts as a simple broker, whilst it is up to the viewer to recognise/parse/process urls (which may only be local to their specific network) and handle invalid URLs/timeouts.

**Comment by railsagainstignorance** [comment]
Question: where would the server get the content titles for displaying in the admin view?

**Comment by JakeChampion** [comment]
It would default to using the url as the title. We can create another API endpoint for viewers to send the title to the server, then the server could update the admin panels

**Comment by AdaRoseCannon** [comment]
This would also allow us to remove the url processing from carousel.
