### ISSUE TITLE
Transient content should override permanent content

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/screens#79]
It's been reported that if content is added to a screen with an expiration date, it will not override content which has been assigned 'until cancelled'. The nature of screens content is that it's in a stack, when new content is pushed, it should go to the top of the stack and override any content, regardless of timing. This does not seem to be the case. 

https://financialtimes.slack.com/archives/ftlabs/p1452853082000779

**Comment by JakeChampion** [comment]
resolved via https://github.com/ftlabs/screens/commit/a1bcbaff0ec13c750dbb5fe48055cac3f99b7f27
