### ISSUE TITLE
cursor still appears on lobby screens

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/screens#84]
https://financialtimes.slack.com/archives/ftlabs/p1453814303000007
1:20 PM] 
tharajan.siva Hey , Question for the people who built the display screen software, is there a way to hide the mouse cursor so it doesn't appear on the screen when the software is running
[1:22 PM] 
Ada Rose Edwards Not aside from moving it to the bottom corner.
[1:30 PM] 
Andrew Betts I think we added some CSS, didn’t we?
[1:30 PM] 
Chris Gathercole thanks for the heads up, @tharajan.siva (and for the mac mini). Discussions underway.
[1:31 PM] 
Ada Rose Edwards that only seems to apply to the page with no content.
[1:31 PM] 
on my browser at least
[1:38 PM] 
tharajan.siva Moving the cursor to the bottom corner is not really working as a solution. If something can be built in to do this automatically it will be useful
[1:52 PM] 
Jake Champion There is CSS for this IIRC

**Comment by JakeChampion** [comment]
Here is the solution Ada has for hiding the cursor on Screens:
Ada Rose Edwards:

> One option I can think of is to make iframe itself 'pointer-events: none;'
> It'll mean the user cannot click on the iframe but the cursor will go invisible
> a click on the page beneath can be used to restore the pointer until the next url change.
> Which seems a pretty sensible solution to me allowing us both hidden cursor but allowing interactivity.
