### ISSUE TITLE
Enterprise License is required

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/screens#87]
In order to deploy the Screens Chrome app as a full screen run-on-boot thing, we need an enterprise account to manage the Chromebits.

**Comment by triblondon** [comment]
1. Talk to Toby about authorising the purchase of a $24 Single App Chrome Device Management License.
2. Sit with Tharajan to add the Chromebit to his Chrome managed devices list, and get it to  boot into the kiosk mode that we want.  If this still requires a Google account as well...
3. Talk to Toby and Luke about creating a new AD (active directory) account that can be used for this, and ideally all dashboard like things. Ideally we should not have to create a 'new starter' for this. :-)

**Comment by seanmtracey** [comment]
Licenses are yet to be acquired, however we are now in discussions with Google to get 5 ( minimum purchase ).

**Comment by seanmtracey** [comment]
Licenses have since been acquired and the devices provisioned.
