### ISSUE TITLE
Nicer transition between carousel items

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/screens#91]
#### Issue

Currently, whenever we change items in one of our carousels, we see a flash of white (while the content loads) which is then replaced by the next item in our carousel. It's quite jarring, and if something fails to load, we're left with a big white screen until the next item comes along, which could be in minutes. 
#### Proposed solution

We know how long content is going to be on the screens for, in the last second or so of the content being visible, we could fade to black by adjusting the iframe/webview opacity and then fade it back in when the new content has loaded. If the content fails to load, we're left with a black (blank) screen, which IMO doesn't immediately give members of the public the impression that something is broken in the same way that a blank white screen does.

**Comment by JakeChampion** [comment]
#### Proposed solution

Preload the next content item in a hidden iframe and only switch if the loading is complete?

**Comment by seanmtracey** [comment]
I'm not a massive fan of tracking the state of multiple iframes/webviews. That said, if implemented correctly, it would be quite robust and would have the benefit of never having a blank screen (providing some content had loaded somewhere)

**Comment by AdaRoseCannon** [comment]
Fixed by #104
